game_window = None
stop = False
window = {'x': 0, 'y': 0, 'width': 0, 'height': 0}
click_positions = []
all_frames = []
global_index = 0
fps = 9

bonuses = [['Bird of Prey', 0], ['Combo King', 0], ['Juggler', 0], ['Backstabber', 0], ['Sweeper', 0],
           ['Clean Sweep', 0], ['Meteor Smash', 0], ['Meteor Clear', 0], ['Meteor Master', 0],
           ['Meteor Survivor', 0], ['Flying Meteor', 0], ['Exceptional Aim', 0], ['Perfect Aim', 0],
           ['All Ground', 0], ['All Aerial', 0], ['All Variations', 0], ['All on One', 0],
           ['Lethal Weapon', 0], ['Berserker', 0], ['Smash King', 0], ['Smash Maniac', 0],
           ['Smash-less', 0], ['Specialist', 0], ['Dedicated Specialist', 0], ['One-Two Punch', 0],
           ['First Strike', 0], ['150% Damage', 0], ['200% Damage', 0], ['250% Damage', 0], ['300% Damage', 0],
           ['350% Damage', 0], ['Heavy Damage', 0], ['Sniper', 0], ['Brawler', 0], ['Precise Aim', 0],
           ['Pitcher', 0], ['Butterfingers', 0], ['All Thumbs', 0], ['Cuddly Bear', 0], ['Compass Tosser', 0],
           ['Throw Down', 0], ['Pummeler', 0], ['Fists of Fury', 0], ['Close Call', 0], ['Opportunist', 0],
           ['Spectator', 0], ['Statue', 0], ['Never Look Back', 0], ['Stiff Knees', 0], ["Run, Don't Walk", 0],
           ['Ambler', 0], ['No Hurry', 0], ['Marathon Man', 0], ['Eagle', 0], ['Aerialist', 0], ['Acrobat', 0],
           ['Cement Shoes', 0], ['Head Banger', 0], ['Elbow Room', 0], ['Power Shielder', 0], ['Shield Buster', 0],
           ['Shattered Shield', 0], ['Shield Stupidity', 0], ['Shield Saver', 0], ['Skid Master', 0],
           ['Rock Climber', 0], ['Edge Hog', 0], ['Cliffhanger', 0], ['Life on the Edge', 0], ['Poser', 0],
           ['Poser Poseur', 0], ['Poser Power', 0], ['Pose Breaker', 0], ['Instant Poser', 0], ['Control Freak', 0],
           ['Button Masher', 0], ['Button Holder', 0], ['Rock Steady', 0], ['Pratfaller', 0], ['Face Planter', 0],
           ['Twinkle Toes', 0], ['Floor Diver', 0], ['No R 4 U', 0], ['Climactic Clash', 0], ['Floored', 0],
           ['Punching Bag', 0], ['Stale Moves', 0], ['Blind Eye', 0], ['Crowd Favorite', 0],
           ['Master of Suspense', 0], ['Lost in Space', 0], ['Lost Luggage', 0], ['Half-Minute Man', 0],
           ['Pacifist', 0], ['Peaceful Warrior', 0], ['Moment of Silence', 0], ['Impervious', 0], ['Immortal', 0],
           ['Switzerland', 0], ['Predator', 0], ['Down, But Not Out', 0], ['Solar Being', 0], ['Stalker', 0],
           ['Bully', 0], ['Coward', 0], ['In the Fray', 0], ['Friendly Foe', 0], ['Center Stage', 0],
           ['Merciful Master', 0], ['Star KO', 0], ['Rocket KO', 0], ['Wimpy KO', 0], ['Bulls-eye KO', 0],
           ['Poser KO', 0], ['Cheap KO', 0], ['Bank-Shot KO', 0], ['Timely KO', 0], ['Special KO', 0],
           ["Hangman's KO", 0], ['KO 64', 0], ['Bubble-Blast KO', 0], ['Sacrificial KO', 0],
           ['Avenger KO', 0], ['Double KO', 0], ['Triple KO', 0], ['Quadruple KO', 0], ['Quintuple KO', 0],
           ['Dead-Weight KO', 0], ['Kiss-the-Floor KO', 0], ['Assisted KO', 0], ['Foresight', 0], ['First to Fall', 0],
           ['Cliff Diver', 0], ['Quitter', 0], ['Shameful Fall', 0], ['World Traveler', 0], ['Ground Pounded', 0],
           ['Environmental Hazard', 0], ['Angelic', 0], ['Magnified Finish', 0], ['Fighter Stance', 0], ['Mystic', 0],
           ['Shooting Star', 0], ['Lucky Number Seven', 0], ['Last Second', 0], ['Lucky Threes', 0], ['Jackpot', 0],
           ['Full Power', 0], ['Item-less', 0], ['Item Specialist', 0], ['Item Chucker', 0], ['Item Smasher', 0],
           ['Capsule KO', 0], ['Carrier KO', 0], ['Weight Lifter', 0], ['Item Catcher', 0], ['Reciprocator', 0],
           ['Item Self-Destruct', 0], ['Triple Items', 0], ['Minimalist', 0], ['Materialist', 0], ['Item Hog', 0],
           ['Item Collector', 0], ['Connoisseur', 0], ['Gourmet', 0], ['Battering Ram', 0], ['Straight Shooter', 0],
           ['Wimp', 0], ['Shape Shifter', 0], ['Chuck Wagon', 0], ['Parasol Finish', 0], ['Gardener Finish', 0],
           ['Flower Finish', 0], ['Super Scoper', 0], ['Screwed Up', 0], ['Screw Attack KO', 0], ['Warp Star KO', 0],
           ['Mycologist', 0], ['Mario Maniac', 0], ['Metal KO', 0], ['Freezie KO', 0], ['Flipper KO', 0],
           ['Mr. Saturn Fan', 0], ['Mrs. Saturn', 0], ['Saturn Siblings', 0], ['Saturn Ringer', 0], ['Giant KO', 0],
           ['Tiny KO', 0], ['Invisible KO', 0], ['Bunny-Hood Blast', 0], ['Vegetarian', 0], ['Heartthrob', 0],
           ['Invincible Finish', 0], ['Invincible KO', 0], ['Beam Swordsman', 0], ['Home-Run King', 0],
           ['Laser Marksman', 0], ['Flame Thrower', 0], ['Hammer Throw', 0], ['Headless Hammer', 0], ['Super Spy', 0],
           ["Bob-omb's Away", 0], ['Bob-omb Squad', 0], ['Pokémon KO', 0], ['Mew Catcher', 0], ['Celebi Catcher', 0],
           ['Goomba KO', 0], ['Koopa KO', 0], ['Paratroopa KO', 0], ['ReDead KO', 0], ['Like Like KO', 0],
           ['Octorok KO', 0], ['Topi KO', 0], ['Polar Bear KO', 0], ['Shy Guy KO', 0], ['First Place', 0],
           ['Last Place', 0], ['Wire to Wire', 0], ['Whipping Boy', 0], ['KO Artist', 0], ['KO Master', 0],
           ['Offensive Artist', 0], ['Offensive Master', 0], ['Frequent Faller', 0], ['Fall Guy', 0],
           ['Self-Destructor', 0], ['Master of Disaster', 0], ['KOs', 0], ['Falls', 0], ['SDs', 0],
           ['Target Master', 0], ['Hobbyist', 0], ['Collector', 0], ['No-Damage Clear', 0], ['No-Miss Clear', 0],
           ['Continuation', 0], ['Speedster', 0], ['Speed Demon', 0], ['Melee Master', 0], ['Classic Clear', 0],
           ['Adventure Clear', 0], ['All-Star Clear', 0], ['Very-Hard Clear', 0], ['Crazy Hand KO', 0], ['Luigi KO', 0],
           ['Link Master', 0], ['Giant Kirby KO', 0], ['Metal Bros. KO', 0], ['Giga Bowser KO', 0]]

halfbonus = int(len(bonuses) / 2) + 1
